### ISSUE TITLE
[description] The description at the top of the page should be complete

### ISSUE THREAD

**Issue by gauri145** [SoftwareEngineeringToolDemos/ICSE-2012-CodeBubbles-old#1]
Criteria for issue: 

At the top of the page, is a project description filled in? 

Provide a description that completely fits in the allotted textbox.

**Comment by mohansammeta** [comment]
Changed the description

**Comment by mohansammeta** [comment]
This issue was moved to SoftwareEngineeringToolDemos/ICSE-2012-CodeBubbles#12
