### ISSUE TITLE
 [vm-youtube] video not describing enough

### ISSUE THREAD

**Issue by rishielnino** [SoftwareEngineeringToolDemos/ICSE-2012-CodeBubbles-old#12]
Criteria for issue: 
VM contains a link to Youtube video on the desktop that shows how to use the tool in the VM?

The video just shows how to open the tool , but not how to get the tool to work.

**Comment by mohansammeta** [comment]
The purpose of the video in VM is to show how to access the tool in VM and start it. As my tool is an IDE, I have placed author's video as well on desktop to describe the entire working of IDE once it is opened (independent from VM details), which contains the demo as well.

**Comment by rishielnino** [comment]
https://piazza.com/class/idk9st8m26917?cid=121
You can see the above piazza question.

The grading rubric of the initial vm submission also says the video should show how to use the tool in the vm.

**Comment by mohansammeta** [comment]
Uploaded a new VM with a demo video explaining working of CodeBubbles with a sample project. Please review it.

**Comment by mohansammeta** [comment]
This issue was moved to SoftwareEngineeringToolDemos/ICSE-2012-CodeBubbles#3
