### ISSUE TITLE
 [vm-license]

### ISSUE THREAD

**Issue by rishielnino** [SoftwareEngineeringToolDemos/ICSE-2012-CodeBubbles-old#13]
Criteria for issue : There is a license file on the desktop that contains all the licenses for the software contained in the VM .

The license file should contain the text rather than the links.

**Comment by mohansammeta** [comment]
This issue was moved to SoftwareEngineeringToolDemos/ICSE-2012-CodeBubbles#1

**Comment by mohansammeta** [comment]
This issue was moved to SoftwareEngineeringToolDemos/ICSE-2012-CodeBubbles#2
