### ISSUE TITLE
[has-source] Missing link to source code

### ISSUE THREAD

**Issue by gauri145** [SoftwareEngineeringToolDemos/ICSE-2012-CodeBubbles-old#2]
Criteria for issue:

Does the project contain source code?

Suggest linking source code (next to checkmark) to the source

**Comment by mohansammeta** [comment]
Added source code link [internal]

**Comment by mohansammeta** [comment]
This issue was moved to SoftwareEngineeringToolDemos/ICSE-2012-CodeBubbles#8
