### ISSUE TITLE
[has-binary] Missing link to binary

### ISSUE THREAD

**Issue by gauri145** [SoftwareEngineeringToolDemos/ICSE-2012-CodeBubbles-old#3]
Criteria for issue: 

Does the project contain one or more binaries ?

Currently, opens to an invalid page. Provide a valid link to executable next to the checkmark.

**Comment by mohansammeta** [comment]
Added this link to Original tool link : 
https://github.com/SoftwareEngineeringToolDemos/ICSE-2012-CodeBubbles/blob/master/bin/bubbles.jar

**Comment by mohansammeta** [comment]
This issue was moved to SoftwareEngineeringToolDemos/ICSE-2012-CodeBubbles#7
