### ISSUE TITLE
[migration] The readme has a checkmark for source code but no link to it

### ISSUE THREAD

**Issue by gauri145** [SoftwareEngineeringToolDemos/ICSE-2012-CodeBubbles-old#4]
Criteria for issue: 

If the project contains source code, does it contain the full history of the project (e.g., was the code properly forked or migrated from another repo)? 

Cannot answer the above till the link to source code is added.

**Comment by mohansammeta** [comment]
The original code was hosted on SourceForge not on github, so the code present in this repo is a snapshot version of that, it won't contain the history as it isn't forked.

**Comment by mohansammeta** [comment]
Can this issue be closed?

**Comment by mohansammeta** [comment]
This issue was moved to SoftwareEngineeringToolDemos/ICSE-2012-CodeBubbles#6
