### ISSUE TITLE
 [original-download-link] Missing download link 

### ISSUE THREAD

**Issue by gauri145** [SoftwareEngineeringToolDemos/ICSE-2012-CodeBubbles-old#5]
Criteria for issue: 

Does the readme link to the original download page?

Suggest adding link for downloading the tool as given in [example](https://github.com/SoftwareEngineeringToolDemos/example-repo)

**Comment by gauri145** [comment]
Added original download link #11

**Comment by mohansammeta** [comment]
This issue was moved to SoftwareEngineeringToolDemos/ICSE-2012-CodeBubbles#11
