### ISSUE TITLE
 [internal-binary] Missing link to binary

### ISSUE THREAD

**Issue by gauri145** [SoftwareEngineeringToolDemos/ICSE-2012-CodeBubbles-old#7]
Criteria for issue: 
Does the readme link to binary in this repo?

Add a valid link to binary for the tool as shown in [example](https://github.com/SoftwareEngineeringToolDemos/example-repo)

**Comment by gauri145** [comment]
Merge pull request #10 from SoftwareEngineeringToolDemos/gauri145

**Comment by mohansammeta** [comment]
Gauri,
I have added the link, please close the issue once you verify it.

**Comment by mohansammeta** [comment]
Gauri,
I am migrating the repository with history, once it is done I will shift these issues there. Please wait on this till then.

**Comment by mohansammeta** [comment]
This issue was moved to SoftwareEngineeringToolDemos/ICSE-2012-CodeBubbles#4
