### ISSUE TITLE
[links-function] Links not working

### ISSUE THREAD

**Issue by gauri145** [SoftwareEngineeringToolDemos/ICSE-2012-CodeBubbles-old#8]
Criteria for issue: 

Do all the links work in the readme?

The link to binary for the tool does not work

**Comment by gauri145** [comment]
It has been added by means of a previous pull request

**Comment by mohansammeta** [comment]
This issue was moved to SoftwareEngineeringToolDemos/ICSE-2012-CodeBubbles#10
