### ISSUE TITLE
[contradiction] Has checkmark but does not link to source

### ISSUE THREAD

**Issue by gauri145** [SoftwareEngineeringToolDemos/ICSE-2012-CodeBubbles-old#9]
Criteria for issue:

Are there any contradictions on the readme (such as it says the tool is open source, but doesn't contain or link to the source code)? 

Add link to source

**Comment by mohansammeta** [comment]
Added link to source

**Comment by mohansammeta** [comment]
This issue was moved to SoftwareEngineeringToolDemos/ICSE-2012-CodeBubbles#9
